/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#include "tcpsocket.h"

#include "servicechecker.h"

ServiceChecker::ServiceChecker ()
		: AbstractChecker (), port (-1)
{
	optionsDescription_.add_options()
	("host", boost::program_options::value<std::string> (), "set host")
	("port", boost::program_options::value<int> (), "set port")
	("connection_string", boost::program_options::value<std::string> (), "set connection string")
	("connection_answer", boost::program_options::value<std::string> (), "set connections answer")
	("question", boost::program_options::value<std::string> (), "set send question")
	("answer", boost::program_options::value<std::string> (), "set good answer")
	;
}

ServiceChecker::~ServiceChecker()
{

}

int ServiceChecker::check_p (int argc, char** argv)
{
	if (!parse (argc, argv)) {
		return HaveError;
	}

	TcpSocket socket (host, port);
	if (!socket.connect()) {
		errorString_ = "ServiceNotRunning";
		return NoError;
	}

	socket.write (connectionString + '\n');
	std::string str;
	socket.read (str, 1024);
	str.resize (str.find ('\n'));
	if (str != connectionAnswer) {
		errorString_ = "ProtocolError";
		return NoError;
	}

	errorString_ = "Connected";

	socket.write (question + '\n');
	socket.read (str, 1024);
	str.resize (str.find ('\n'));
	if (str != answer) {
		errorString_ = "ServiceIsWork";
		return HaveError;
	}

	errorString_ = "ServiceNotWork";
	return NoError;
}

bool ServiceChecker::parse (int argc, char** argv)
{
	try {
		boost::program_options::variables_map vm;
		boost::program_options::store (boost::program_options::parse_command_line (argc, argv, optionsDescription_), vm);
		boost::program_options::notify (vm);

		if (vm.count ("host")) {
			host = vm ["host"].as<std::string>();
		} else {
			errorString_ = "Host not set.\n";
			return false;
		}

		if (vm.count ("port")) {
			port = vm ["port"].as<int>();
		} else {
			errorString_ = "Port not set.\n";
			return false;
		}

		if (vm.count ("connection_string")) {
			connectionString = vm ["connection_string"].as<std::string>();
		} else {
			errorString_ = "Connection string not set.\n";
			return false;
		}

		if (vm.count ("connection_answer")) {
			connectionAnswer = vm ["connection_answer"].as<std::string>();
		} else {
			errorString_ = "Connection answer not set.\n";
			return false;
		}

		if (vm.count ("question")) {
			question = vm ["question"].as<std::string>();
		} else {
			errorString_ = "Question not set.\n";
			return false;
		}

		if (vm.count ("answer")) {
			answer = vm ["answer"].as<std::string>();
		} else {
			errorString_ = "Answer not set.\n";
			return false;
		}
	} catch (...) {
		errorString_ = "Bad parameters";
		return false;
	}

	return true;
}
