/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef TCPSOCKET_H
#define TCPSOCKET_H

#include <string>
#include <boost/asio.hpp>
#include <boost/asio/io_service.hpp>

class TcpSocket
{
	
public:
	TcpSocket ();
	TcpSocket (const std::string& host, int port);
	
	~TcpSocket ();
	
	std::string host () const
	{ return host_;}
	void setHost (const std::string& host)
	{ host_ = host;}
	
	int port () const
	{ return port_;}
	void setPort (int port)
	{ port_ = port;}
	
	bool connect ();
	
	int read (char *data, int maxSize);
	int read (std::string &data, int maxSize);
	
	int write (const char* data, int maxSize);
	int write (const std::string& str)
	{ return write (str.c_str (), str.size ());}
	
private:
	TcpSocket (const TcpSocket&);
	TcpSocket& operator= (const TcpSocket&);
	
private:
	std::string host_;
	int port_;
	boost::asio::io_service io_service_;
	boost::asio::ip::tcp::socket socket_;
};

#endif // TCPSOCKET_H
